AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
